
server:
  port: 4000

spring:
  application:
    name: gate_way_service
  cloud:
    gateway:
      routes:
        - id: user
          uri:
            http://localhost:8000/
          predicates:
            - Path=/student/**
        - id: mark
          uri:
            http://localhost:8761/
          predicates:
            - Path=/mark/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka